-- FULL SETUP SCRIPT (Run this once to create everything)

-- 1. CLEANUP (Drop existing tables to avoid conflicts)
drop table if exists public.likes;
drop table if exists public.comments;
drop table if exists public.predictions;
drop table if exists public.users;

-- 2. USERS TABLE (Modified for Telegram Auth)
create table public.users (
  id text primary key, -- Telegram ID as string
  telegram_id bigint unique,
  username text,
  display_name text,
  role text default 'Çaylak',
  rank text default 'Çaylak', -- Tracking column
  login_count int default 0, -- Tracking column
  last_seen_at timestamp with time zone default timezone('utc'::text, now()), -- Tracking column
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table public.users enable row level security;

-- Policies (Allow App to Read/Write)
create policy "Enable read access for all users" on users for select using (true);
create policy "Enable insert access for all users" on users for insert with check (true);
create policy "Enable update access for all users" on users for update using (true);

-- 3. PREDICTIONS TABLE
create table public.predictions (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) not null,
  items jsonb not null,
  total_odds numeric,
  confidence int,
  analysis text,
  status text default 'PENDING',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.predictions enable row level security;
create policy "Enable read access for all users" on predictions for select using (true);
create policy "Enable insert access for all users" on predictions for insert with check (true);
create policy "Enable update access for all users" on predictions for update using (true);

-- 4. COMMENTS TABLE
create table public.comments (
  id bigint generated by default as identity primary key,
  prediction_id bigint references public.predictions(id) on delete cascade not null,
  user_id text references public.users(id) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;
create policy "Enable read access for all users" on comments for select using (true);
create policy "Enable insert access for all users" on comments for insert with check (true);

-- 5. LIKES TABLE
create table public.likes (
  prediction_id bigint references public.predictions(id) on delete cascade not null,
  user_id text references public.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (prediction_id, user_id)
);

alter table public.likes enable row level security;
create policy "Enable read access for all users" on likes for select using (true);
create policy "Enable insert access for all users" on likes for insert with check (true);
create policy "Enable delete access for all users" on likes for delete using (true);
