-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS TABLE
create table public.users (
  id uuid references auth.users not null primary key, -- Links to Supabase Auth
  telegram_id bigint unique,
  username text,
  display_name text,
  role text default 'Çaylak',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;

-- Policies for Users
create policy "Public profiles are viewable by everyone."
  on users for select
  using ( true );

create policy "Users can insert their own profile."
  on users for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on users for update
  using ( auth.uid() = id );

-- PREDICTIONS TABLE
create table public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  items jsonb not null, -- Stores array of matches
  total_odds numeric,
  confidence int,
  analysis text,
  status text default 'PENDING', -- PENDING, WON, LOST
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.predictions enable row level security;

-- Policies for Predictions
create policy "Predictions are viewable by everyone."
  on predictions for select
  using ( true );

create policy "Authenticated users can insert predictions."
  on predictions for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update their own predictions."
  on predictions for update
  using ( auth.uid() = user_id );

-- COMMENTS TABLE
create table public.comments (
  id bigint generated by default as identity primary key,
  prediction_id bigint references public.predictions(id) on delete cascade not null,
  user_id uuid references public.users(id) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.comments enable row level security;

-- Policies for Comments
create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on comments for insert
  with check ( auth.role() = 'authenticated' );

-- LIKES TABLE
create table public.likes (
  prediction_id bigint references public.predictions(id) on delete cascade not null,
  user_id uuid references public.users(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (prediction_id, user_id)
);

-- Enable RLS
alter table public.likes enable row level security;

-- Policies for Likes
create policy "Likes are viewable by everyone."
  on likes for select
  using ( true );

create policy "Authenticated users can insert likes."
  on likes for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can delete their own likes."
  on likes for delete
  using ( auth.uid() = user_id );
